### ISSUE TITLE
Using deprecated library "request" for typings

### ISSUE THREAD

**Issue by dkontorovskyy** [configcat/configcat-publicapi-node-client#2]
If you're not sure whether your problem is specifically related to this repository, or to the ConfigCat service overall, please contact the [ConfigCat support](https://configcat.com/support). This issue tracker is intended only for feedback on the content of this repository. 

### Describe the bug
Using deprecated library "request" for typings

### To reproduce

Steps to reproduce the behavior.

### Expected behavior
This library should've been deprecated as it's not maintained for multiple years and it's prone to vulnerabilities

**Comment by novalisdenahi** [comment]
Hi @dkontorovskyy,

Thanks for the feedback!
We will check the problem and get back to you as soon as possible with an answer.

**Comment by novalisdenahi** [comment]
Hi @dkontorovskyy,

We will replace the `request` dependency with `axios` in the future.
I leave this issue open, so you can see when we change the dependency. 

Best Regards,
Daniel

**Comment by novalisdenahi** [comment]
Hi @dkontorovskyy,

I'm happy to inform you that we released the [v2.0.0](https://github.com/configcat/configcat-publicapi-node-client/releases/tag/v2.0.0) where we replaced the `request` dependency with `axios`.

Best Regards,
Daniel
